export const seoList = [
  {
    category: "csv-fixer",
    action: "add-column",
    path: "/csv-fixer/add-column",
  },
  {
    category: "csv-fixer",
    action: "remove-column",
    path: "/csv-fixer/remove-column",
  },
  {
    category: "csv-fixer",
    action: "rename-column",
    path: "/csv-fixer/rename-column",
  },
  {
    category: "csv-fixer",
    action: "reorder-columns",
    path: "/csv-fixer/reorder-columns",
  },
  {
    category: "csv-fixer",
    action: "merge-columns",
    path: "/csv-fixer/merge-columns",
  },
  {
    category: "csv-fixer",
    action: "split-column",
    path: "/csv-fixer/split-column",
  },
  {
    category: "csv-fixer",
    action: "calculate-column",
    path: "/csv-fixer/calculate-column",
  },
  {
    category: "csv-fixer",
    action: "fix-delimiter",
    path: "/csv-fixer/fix-delimiter",
  },
  {
    category: "csv-fixer",
    action: "auto-detect-delimiter",
    path: "/csv-fixer/auto-detect-delimiter",
  },
  {
    category: "csv-fixer",
    action: "normalize-headers",
    path: "/csv-fixer/normalize-headers",
  },
  {
    category: "csv-fixer",
    action: "lowercase-headers",
    path: "/csv-fixer/lowercase-headers",
  },
  {
    category: "csv-fixer",
    action: "trim-whitespace",
    path: "/csv-fixer/trim-whitespace",
  },
  {
    category: "csv-fixer",
    action: "fill-missing-values",
    path: "/csv-fixer/fill-missing-values",
  },
  {
    category: "csv-fixer",
    action: "drop-null-rows",
    path: "/csv-fixer/drop-null-rows",
  },
  {
    category: "csv-fixer",
    action: "deduplicate-rows",
    path: "/csv-fixer/deduplicate-rows",
  },
  {
    category: "csv-fixer",
    action: "type-inference",
    path: "/csv-fixer/type-inference",
  },
  {
    category: "csv-fixer",
    action: "cast-column",
    path: "/csv-fixer/cast-column",
  },
  {
    category: "csv-fixer",
    action: "date-normalization",
    path: "/csv-fixer/date-normalization",
  },
  {
    category: "csv-fixer",
    action: "encoding-fix",
    path: "/csv-fixer/encoding-fix",
  },
  {
    category: "csv-fixer",
    action: "escape-quotes",
    path: "/csv-fixer/escape-quotes",
  },
  {
    category: "data-cleaning",
    action: "remove-outliers",
    path: "/data-cleaning/remove-outliers",
  },
  {
    category: "data-cleaning",
    action: "impute-mean",
    path: "/data-cleaning/impute-mean",
  },
  {
    category: "data-cleaning",
    action: "impute-median",
    path: "/data-cleaning/impute-median",
  },
  {
    category: "data-cleaning",
    action: "impute-mode",
    path: "/data-cleaning/impute-mode",
  },
  {
    category: "data-cleaning",
    action: "standardize-values",
    path: "/data-cleaning/standardize-values",
  },
  {
    category: "data-cleaning",
    action: "normalize-text",
    path: "/data-cleaning/normalize-text",
  },
  {
    category: "data-cleaning",
    action: "fix-typos",
    path: "/data-cleaning/fix-typos",
  },
  {
    category: "data-cleaning",
    action: "regex-replace",
    path: "/data-cleaning/regex-replace",
  },
  {
    category: "data-cleaning",
    action: "remove-invalid-rows",
    path: "/data-cleaning/remove-invalid-rows",
  },
  {
    category: "data-cleaning",
    action: "schema-validation",
    path: "/data-cleaning/schema-validation",
  },
  {
    category: "data-cleaning",
    action: "range-validation",
    path: "/data-cleaning/range-validation",
  },
  {
    category: "data-cleaning",
    action: "uniqueness-check",
    path: "/data-cleaning/uniqueness-check",
  },
  {
    category: "data-cleaning",
    action: "null-analysis",
    path: "/data-cleaning/null-analysis",
  },
  {
    category: "data-cleaning",
    action: "consistency-check",
    path: "/data-cleaning/consistency-check",
  },
  {
    category: "query-to-csv",
    action: "natural-language",
    path: "/query-to-csv/natural-language",
  },
  {
    category: "query-to-csv",
    action: "sql-like",
    path: "/query-to-csv/sql-like",
  },
  { category: "query-to-csv", action: "hive", path: "/query-to-csv/hive" },
  {
    category: "query-to-csv",
    action: "spark-sql",
    path: "/query-to-csv/spark-sql",
  },
  { category: "query-to-csv", action: "presto", path: "/query-to-csv/presto" },
  { category: "query-to-csv", action: "trino", path: "/query-to-csv/trino" },
  {
    category: "query-to-csv",
    action: "postgres",
    path: "/query-to-csv/postgres",
  },
  { category: "query-to-csv", action: "mysql", path: "/query-to-csv/mysql" },
  {
    category: "query-to-csv",
    action: "mongodb",
    path: "/query-to-csv/mongodb",
  },
  {
    category: "query-to-csv",
    action: "elasticsearch",
    path: "/query-to-csv/elasticsearch",
  },
  {
    category: "query-to-csv",
    action: "parquet",
    path: "/query-to-csv/parquet",
  },
  { category: "query-to-csv", action: "orc", path: "/query-to-csv/orc" },
  { category: "notebook", action: "run-cell", path: "/notebook/run-cell" },
  { category: "notebook", action: "run-all", path: "/notebook/run-all" },
  {
    category: "notebook",
    action: "stop-kernel",
    path: "/notebook/stop-kernel",
  },
  {
    category: "notebook",
    action: "restart-kernel",
    path: "/notebook/restart-kernel",
  },
  {
    category: "notebook",
    action: "clear-output",
    path: "/notebook/clear-output",
  },
  {
    category: "notebook",
    action: "save-checkpoint",
    path: "/notebook/save-checkpoint",
  },
  {
    category: "notebook",
    action: "convert-to-script",
    path: "/notebook/convert-to-script",
  },
  {
    category: "notebook",
    action: "convert-to-html",
    path: "/notebook/convert-to-html",
  },
  {
    category: "notebook",
    action: "convert-to-pdf",
    path: "/notebook/convert-to-pdf",
  },
  {
    category: "notebook",
    action: "parameterize",
    path: "/notebook/parameterize",
  },
  {
    category: "notebook",
    action: "schedule-run",
    path: "/notebook/schedule-run",
  },
  {
    category: "notebook",
    action: "version-diff",
    path: "/notebook/version-diff",
  },
  {
    category: "notebook",
    action: "trust-notebook",
    path: "/notebook/trust-notebook",
  },
  {
    category: "ai-notebook",
    action: "explain-cell",
    path: "/ai-notebook/explain-cell",
  },
  {
    category: "ai-notebook",
    action: "refactor-code",
    path: "/ai-notebook/refactor-code",
  },
  {
    category: "ai-notebook",
    action: "optimize-query",
    path: "/ai-notebook/optimize-query",
  },
  {
    category: "ai-notebook",
    action: "generate-sql",
    path: "/ai-notebook/generate-sql",
  },
  {
    category: "ai-notebook",
    action: "generate-pyspark",
    path: "/ai-notebook/generate-pyspark",
  },
  {
    category: "ai-notebook",
    action: "auto-comment",
    path: "/ai-notebook/auto-comment",
  },
  {
    category: "ai-notebook",
    action: "find-bug",
    path: "/ai-notebook/find-bug",
  },
  {
    category: "ai-notebook",
    action: "explain-error",
    path: "/ai-notebook/explain-error",
  },
  {
    category: "ai-notebook",
    action: "suggest-visualization",
    path: "/ai-notebook/suggest-visualization",
  },
  {
    category: "ai-notebook",
    action: "data-summary",
    path: "/ai-notebook/data-summary",
  },
  {
    category: "ai-notebook",
    action: "schema-inference",
    path: "/ai-notebook/schema-inference",
  },
  {
    category: "ai-notebook",
    action: "code-translation",
    path: "/ai-notebook/code-translation",
  },
  { category: "spark", action: "load-csv", path: "/spark/load-csv" },
  { category: "spark", action: "load-parquet", path: "/spark/load-parquet" },
  { category: "spark", action: "load-orc", path: "/spark/load-orc" },
  { category: "spark", action: "write-csv", path: "/spark/write-csv" },
  { category: "spark", action: "write-parquet", path: "/spark/write-parquet" },
  {
    category: "spark",
    action: "cache-dataframe",
    path: "/spark/cache-dataframe",
  },
  { category: "spark", action: "repartition", path: "/spark/repartition" },
  { category: "spark", action: "coalesce", path: "/spark/coalesce" },
  {
    category: "spark",
    action: "join-optimizer",
    path: "/spark/join-optimizer",
  },
  {
    category: "spark",
    action: "window-functions",
    path: "/spark/window-functions",
  },
  { category: "spark", action: "udf-register", path: "/spark/udf-register" },
  {
    category: "spark",
    action: "streaming-ingest",
    path: "/spark/streaming-ingest",
  },
  {
    category: "spark",
    action: "streaming-aggregate",
    path: "/spark/streaming-aggregate",
  },
  { category: "hive", action: "create-table", path: "/hive/create-table" },
  { category: "hive", action: "drop-table", path: "/hive/drop-table" },
  { category: "hive", action: "alter-table", path: "/hive/alter-table" },
  { category: "hive", action: "load-data", path: "/hive/load-data" },
  { category: "hive", action: "partition-add", path: "/hive/partition-add" },
  {
    category: "hive",
    action: "partition-repair",
    path: "/hive/partition-repair",
  },
  {
    category: "hive",
    action: "partition-prune",
    path: "/hive/partition-prune",
  },
  { category: "hive", action: "bucket-table", path: "/hive/bucket-table" },
  { category: "hive", action: "serde-detect", path: "/hive/serde-detect" },
  {
    category: "hive",
    action: "query-optimizer",
    path: "/hive/query-optimizer",
  },
  {
    category: "hive",
    action: "statistics-analyze",
    path: "/hive/statistics-analyze",
  },
  { category: "etl", action: "extract", path: "/etl/extract" },
  { category: "etl", action: "transform", path: "/etl/transform" },
  { category: "etl", action: "load", path: "/etl/load" },
  {
    category: "etl",
    action: "incremental-load",
    path: "/etl/incremental-load",
  },
  { category: "etl", action: "full-refresh", path: "/etl/full-refresh" },
  { category: "etl", action: "schema-mapping", path: "/etl/schema-mapping" },
  { category: "etl", action: "column-mapping", path: "/etl/column-mapping" },
  { category: "etl", action: "data-enrichment", path: "/etl/data-enrichment" },
  { category: "etl", action: "lookup-join", path: "/etl/lookup-join" },
  { category: "etl", action: "surrogate-key", path: "/etl/surrogate-key" },
  {
    category: "etl",
    action: "change-data-capture",
    path: "/etl/change-data-capture",
  },
  { category: "dataset", action: "upload", path: "/dataset/upload" },
  { category: "dataset", action: "download", path: "/dataset/download" },
  { category: "dataset", action: "preview", path: "/dataset/preview" },
  { category: "dataset", action: "profile", path: "/dataset/profile" },
  { category: "dataset", action: "version", path: "/dataset/version" },
  { category: "dataset", action: "lineage", path: "/dataset/lineage" },
  { category: "dataset", action: "metadata", path: "/dataset/metadata" },
  { category: "dataset", action: "sample", path: "/dataset/sample" },
  { category: "dataset", action: "statistics", path: "/dataset/statistics" },
  { category: "dataset", action: "delete", path: "/dataset/delete" },
  {
    category: "visualization",
    action: "line-chart",
    path: "/visualization/line-chart",
  },
  {
    category: "visualization",
    action: "bar-chart",
    path: "/visualization/bar-chart",
  },
  {
    category: "visualization",
    action: "pie-chart",
    path: "/visualization/pie-chart",
  },
  {
    category: "visualization",
    action: "histogram",
    path: "/visualization/histogram",
  },
  {
    category: "visualization",
    action: "boxplot",
    path: "/visualization/boxplot",
  },
  {
    category: "visualization",
    action: "heatmap",
    path: "/visualization/heatmap",
  },
  {
    category: "visualization",
    action: "scatter",
    path: "/visualization/scatter",
  },
  {
    category: "visualization",
    action: "time-series",
    path: "/visualization/time-series",
  },
  {
    category: "visualization",
    action: "dashboard",
    path: "/visualization/chat",
  },
  {
    category: "visualization",
    action: "export",
    path: "/visualization/export",
  },
  { category: "ml", action: "train", path: "/ml/train" },
  { category: "ml", action: "validate", path: "/ml/validate" },
  { category: "ml", action: "test", path: "/ml/test" },
  { category: "ml", action: "cross-validation", path: "/ml/cross-validation" },
  {
    category: "ml",
    action: "feature-engineering",
    path: "/ml/feature-engineering",
  },
  {
    category: "ml",
    action: "feature-selection",
    path: "/ml/feature-selection",
  },
  { category: "ml", action: "scaling", path: "/ml/scaling" },
  { category: "ml", action: "encoding", path: "/ml/encoding" },
  {
    category: "ml",
    action: "hyperparameter-search",
    path: "/ml/hyperparameter-search",
  },
  { category: "ml", action: "model-compare", path: "/ml/model-compare" },
  { category: "ml", action: "model-export", path: "/ml/model-export" },
  { category: "ops", action: "job-status", path: "/ops/job-status" },
  { category: "ops", action: "job-logs", path: "/ops/job-logs" },
  { category: "ops", action: "job-retry", path: "/ops/job-retry" },
  { category: "ops", action: "job-cancel", path: "/ops/job-cancel" },
  { category: "ops", action: "resource-usage", path: "/ops/resource-usage" },
  { category: "ops", action: "cost-estimation", path: "/ops/cost-estimation" },
  { category: "ops", action: "alerting", path: "/ops/alerting" },
  { category: "ops", action: "audit-log", path: "/ops/audit-log" },
  { category: "ops", action: "access-control", path: "/ops/access-control" },
  {
    category: "ops",
    action: "secret-management",
    path: "/ops/secret-management",
  },
  {
    category: "governance",
    action: "data-access",
    path: "/governance/data-access",
  },
  {
    category: "governance",
    action: "column-masking",
    path: "/governance/column-masking",
  },
  {
    category: "governance",
    action: "row-filtering",
    path: "/governance/row-filtering",
  },
  {
    category: "governance",
    action: "pii-detection",
    path: "/governance/pii-detection",
  },
  {
    category: "governance",
    action: "pii-redaction",
    path: "/governance/pii-redaction",
  },
  {
    category: "governance",
    action: "retention-policy",
    path: "/governance/retention-policy",
  },
  {
    category: "governance",
    action: "compliance-report",
    path: "/governance/compliance-report",
  },
];
